"""Initial migration

Revision ID: 53687d98875f
Revises: 
Create Date: 2025-10-10 13:56:09.224043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53687d98875f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('seance_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('seat_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('paid', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'seance', ['seance_id'], ['id'])
        batch_op.create_foreign_key(None, 'seat', ['seat_id'], ['id'])
        batch_op.drop_column('heure')
        batch_op.drop_column('salle')
        batch_op.drop_column('nom')
        batch_op.drop_column('email')
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('nom', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('salle', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('heure', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('created_at')
        batch_op.drop_column('amount')
        batch_op.drop_column('paid')
        batch_op.drop_column('seat_id')
        batch_op.drop_column('seance_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
